theme: jekyll-theme-minimal
title: Board Game Cheat Sheets
description: Quick reference guides for board games

collections:
  games:
    output: true
    permalink: /games/:path/

defaults:
  - scope:
      path: ""
      type: "games"
    values:
      layout: "game" 